/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package matspoon.k8sbasic;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        logger.info("Started K8s Basic Application");
        SpringApplication.run(App.class, args);
    }
}
