spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      leak-detection-threshold: 0
      auto-commit: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      "[hibernate.hbm2ddl.jdbc_metadata_extraction_strategy]": individually
logging:
  level:
    "[com.zaxxer.hikari.pool.ProxyConnection]": ERROR